version: 0.2

env:
  variables:
    FUNCTION_NAME: "my-lambda-function"
    S3_BUCKET_NAME: "sshriobucket"

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - cd $CODEBUILD_SRC_DIR/src
      - cp .env.dev .env
      - npm install

  build:
    commands:
      - echo "Building the Lambda package..."
      - zip -r package.zip ./ -x "package*" ".git*"

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp package.zip s3://$S3_BUCKET_NAME/build_output.zip # Upload the package to S3
      - echo "S3 upload complete."
      - echo "Updating Lambda function..."
      - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key build_output.zip
      - echo "Lambda function updated successfully."

artifacts:
  files:
    - src/package.zip
